---
all:
  children:
    webservers:
      hosts:
        web_server:
          ansible_host: "{{ web_server_ip | default('192.168.0.11') }}"
          server_role: "webserver"
          db_host: "{{ db_server_ip | default('192.168.0.12') }}"

    dbservers:
      hosts:
        db_server:
          ansible_host: "{{ db_server_ip | default('192.168.0.12') }}"
          server_role: "database"
