---
all:
  children:
    webservers:
      hosts:
        web_server:
          ansible_host: "{{ web_server_ip | default('192.168.56.10') }}"
          server_role: "webserver"
          db_host: "{{ db_server_ip | default('192.168.56.20') }}"

    dbservers:
      hosts:
        db_server:
          ansible_host: "{{ db_server_ip | default('192.168.56.20') }}"
          server_role: "database"
